# Generated by Django 3.0.4 on 2021-01-11 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postCode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='fir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrn', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ruleCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrn', models.CharField(max_length=10)),
                ('reg_owner', models.CharField(max_length=100)),
                ('reg_email', models.EmailField(max_length=254, null=True)),
                ('reg_phone', models.CharField(max_length=10)),
                ('vehicleType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vehicleType')),
            ],
        ),
        migrations.CreateModel(
            name='defaulter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrn', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('checkPost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.checkPost')),
                ('ruleCat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ruleCat')),
            ],
        ),
    ]
