# Generated by Django 3.0.4 on 2021-01-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpost',
            name='district',
            field=models.CharField(default='Haryana', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpost',
            name='state',
            field=models.CharField(default='Karnal', max_length=30),
            preserve_default=False,
        ),
    ]
